### ISSUE TITLE
Missing documentation for (likely) rate limit of messages to team members

### ISSUE THREAD

**Issue by siwica** [lichess-org/api#111]
Trying out the API endpoint to message all members of a team (see https://lichess.org/api#operation/teamIdPmAll) I encountered some sort of rate limit as sending a subsequent message only succeeded ~5min after sending the last succesful one. This behavior, however, is currently not documented.

**Comment by ornicar** [comment]
https://github.com/ornicar/lila/commit/7962a938ccdf13c1b958a57b867b4d290db2115a

**Comment by siwica** [comment]
Shouldn't the API docs now contain a 429 response rather than 400?

Also, would you mind documenting the specifics of the rate limit or is that intentionally left unspecified to discourage spamming?

**Comment by ornicar** [comment]
The API doesn't mention 429 responses because they can happen on every endpoint.

The rate limit strategy is not documented because it's multi-layered, complex, and often changing.
