### ISSUE TITLE
how create "play with the computer" by api? thx

### ISSUE THREAD

**Issue by shinhwagk** [lichess-org/api#113]
If not, can add it?

**Comment by ornicar** [comment]
why do you need it?

**Comment by shinhwagk** [comment]
I work on a project，so need board api to do the test, but create seek will interfere with other players. 
I can create computer by web or phone yet, then use board api. if "play with the computer" exist will better

**Comment by ornicar** [comment]
you should be able to use this https://lichess.org/api#operation/challengeAi

**Comment by shinhwagk** [comment]
ok thanks
