### ISSUE TITLE
Fetching https://lichess.org/study with CORS error

### ISSUE THREAD

**Issue by Beddie** [lichess-org/api#119]
Fetching url "https://lichess.org/study/j3GLKW46.pgn" does not work from a React app.

**Already tried**
- Providing extra headers does not solve the issue.
- Using mode: no-cors does not solve the issue either, because an opaque respons is returned from lichess.
- Fetching this url from a browser does work.

**Question**
- How do i solve this to be able fetching "https://lichess.org/study/j3GLKW46.pgn" from my React app.

Thanks in advance!

**Comment by niklasf** [comment]
Working on a CORS compatible API for study PGNs in https://github.com/ornicar/lila/pull/9236.

**Comment by niklasf** [comment]
The next update (likely in a few days) will have https://github.com/lichess-org/api/commit/81318006cab70b5ad304b5f13201c4ce617390b5. The time of the last update is always shown on https://lichess.org/source#version.
