### ISSUE TITLE
problem with Redirect callback in OAuth app example

### ISSUE THREAD

**Issue by digither** [lichess-org/api#13]
I try https://github.com/lichess-org/api/tree/master/example/oauth-authorization-code
When the user is not previously connected, the redirection in the callback fails, just after the login, it sends to 404. It seems that it redirects to

> https://lichess.org/https://oauth.lichess.org/oauth/authorize ? response_type = code ....

 the correct redirection would be to:

> https://oauth.lichess.org/oauth/authorize?response_type=code .... .

If user is previously connected fine work.
I do not know how I can solve this problem. Thank you for the attention and for your great work for the community

**Comment by ddugovic** [comment]
Same here; both the example application and http://relaychess.mooo.com/ logins are broken.

**Comment by digither** [comment]
The problem persists, maybe my code is wrong, but I do not see it possible if redirection works with the user already registered
![problem_with_redirect](https://user-images.githubusercontent.com/43046648/54472777-b8c0f800-47ce-11e9-90da-dee290da54eb.png)

**Comment by niklasf** [comment]
It might just be that the bugfix has not been deployed to production yet.

**Comment by digither** [comment]
> It might just be that the bugfix has not been deployed to production yet.

Thank you very much and congratulations for the great project lichess.

**Comment by ornicar** [comment]
it has been deployed
