### ISSUE TITLE
The https://lichess.org/api/cloud-eval API does not accept valid FENs

### ISSUE THREAD

**Issue by dimplayschess** [lichess-org/api#147]
Try this:

https://lichess.org/api/cloud-eval?fen=rnbqkb1r/pppnp2p/4p1Q1/3p4/3P4/8/PPP2PPP/RNB1KBNR b KQkq - 0 6

The abovre fen:

rnbqkb1r/pppnp2p/4p1Q1/3p4/3P4/8/PPP2PPP/RNB1KBNR b KQkq - 0 6

is valid.

You can take a look here:

https://fen2png.com/api/?fen=rnbqkb1r/pppnp2p/4p1Q1/3p4/3P4/8/PPP2PPP/RNB1KBNR%20b%20KQkq%20-%200%206

This is cuurently blocking my !analysis command I am developing for my chess bot.

Can you take a look into the issue?

Thanks.

Dimpoul on Twitch
DImplayschess on Lichess.org

**Comment by ornicar** [comment]
It says 404 Not found because there's no stored analysis for that position.
