### ISSUE TITLE
Challenged API lag value inaccurate

### ISSUE THREAD

**Issue by ddugovic** [lichess-org/api#15]
https://lichess.org/api#operation/apiStreamEvent
Latency from USA to lichess.org is 70 ms, not 4 ms (log by https://github.com/ddugovic/lichess-bot-1/tree/variant):

```
Apr 06 16:32:49 vps178028 lichess-bot[30910]: Accepting challenge {v2nF7sZr created {toadofsky Toadofsky  1942 true true 4} {standard} false bullet random}
```

**Comment by ornicar** [comment]
I don't understand.

**Comment by ddugovic** [comment]
When my bot is receiving responses from `/api/stream/event` (when I as Toadofsky used a browser to challenge my bot), my bot received the `challenge` HTTP response body `{... challenger {toadofsky ... 4} ...}` indicating that my lag time is 4ms.

From http://lichess.org/lag I see my ping time is over 100ms (although the server latency is 4ms).

**Comment by ornicar** [comment]
It's not milliseconds, it's the number of bars, like displayed on the challenge UI:

![](https://i.imgur.com/1I7BXbU.png)

Formula: https://github.com/ornicar/lila/blob/acd418a7ed13fec338f01151304c086739fa1fe7/modules/socket/src/main/UserLagCache.scala#L19-L24
