### ISSUE TITLE
Turn is fuzzy for 3 turns at turn 5.

### ISSUE THREAD

**Issue by cojoko** [lichess-org/api#151]
I know the last three turns get hidden to avoid cheatbots, but AFAIK there is no way to get which color plays next with 100% accuracy from turns 5 - 8. I am using `moves.length % 2` to return whose turn it is to play, so unless there is a cleaner way that I am missing, would there be any harm in adding an endpoint or field in the game data indicating turn?

I assume there is a reason I am missing for this omission (or i am blind to an extant solution), but I would be happy to submit a PR for this feature if not.

**Comment by cojoko** [comment]
@ornicar bump

**Comment by ornicar** [comment]
> Otherwise, how would you suggest getting all active games for a user where it is their turn?

With https://lichess.org/api#operation/apiAccountPlaying. It has an `isMyTurn` field.
