### ISSUE TITLE
Documentation - title list by strength

### ISSUE THREAD

**Issue by eyal282** [lichess-org/api#152]
![Screenshot_142](https://user-images.githubusercontent.com/39803639/139718191-54325576-0a42-44d8-a799-286a47183cd8.png)

I was told these are wrong, and it appears to be. Can someone order them by strength and of course keep LM and BOT last?

It confused me a lot and may confuse others by how women have titles which can go two titles below the international ones.

**Comment by benediktwerner** [comment]
The list only enumerates the possible values. There is no meaning to the order.

**Comment by eyal282** [comment]
> The list only enumerates the possible values. There is no meaning to the order.

Problem is I couldn't figure out what is stronger than whom, and I get no info on it.
