### ISSUE TITLE
trying to broadcast tournament

### ISSUE THREAD

**Issue by eduardoworrel** [lichess-org/api#179]
hello nobles

I'm trying to create an application that follows Brazilian players in live tournaments.

After failing miserably to use the endpoint https://lichess.org/api/stream/broadcast/round/{broadcastRoundId}.pgn
receiving status 200 but without response body, I decided to go down an alternative path that met my needs provisionally.

I share with you in the hope of solving my problem (show the players' clock) or being guided in the best way to do

After days of frustration I saw this graceful endpoint https://lichess.org/study/k2iftQci/multi-board?page=1&playing=false

That's almost all I need, the FEN and player name&rating, but player time and clock are left out

As the endpoint is restricted I used the following resources

simple web scraping
https://github.com/eduardoworrel/colabbox/blob/master/web/steal-fen-from-lichess-website/index.ts

websocket to omit client call
https://github.com/eduardoworrel/colabbox/blob/master/web/background-update-fen-websocket%20/app.py

Then...
I'm crazy? is there a happy path?

if not, is it possible to provide something similar?

Simple as a set of FENs, but with some milestone of the player's clock and which player is pending

**Comment by ornicar** [comment]
Use https://lichess.org/api#operation/broadcastStreamRoundPgn, it's the only correct way.

See it working: `curl 'https://lichess.org/api/stream/broadcast/round/k2iftQci.pgn'

**Comment by eduardoworrel** [comment]
"See how it receives new updates on moves immediately within the same single request"

where can i find an example? @ornicar

**Comment by ornicar** [comment]
I just gave you one:

`curl 'https://lichess.org/api/stream/broadcast/round/k2iftQci.pgn`
