### ISSUE TITLE
User ratings

### ISSUE THREAD

**Issue by ddugovic** [lichess-org/api#18]
https://lichess.org/@/lichess has played 0 games however https://lichess.org/api/user/lichess includes bullet, blitz, etc. ratings

Observed by Discord user Maj0r, author of https://github.com/Maj0rites/Maj0rs-lichess-bot/ who is reading a PDF https://buildmedia.readthedocs.org/media/pdf/python-lichess/latest/python-lichess.pdf and somehow assuming that's the Lichess API specification.  Thoughts @cyanfish (perhaps that PDF should reference the official API URL)?

**Comment by ornicar** [comment]
Assume 0 games when perf is absent
