### ISSUE TITLE
Missing enum in schema for `VariantKey`: `fromPosition`

### ISSUE THREAD

**Issue by mcognetta** [lichess-org/api#181]
The game variant enum, `VariantKey` ([definition](https://github.com/lichess-org/api/blob/master/doc/specs/lichess-api.yaml#L6622)), has an undocumented value `fromPosition`. For example, exporting [this game](https://lichess.org/dHnTvQv3), which was started from specific FEN, returns a JSON with `"variant": "fromPosition"`.

This enum value is not mentioned in the Lichess API docs: https://lichess.org/api#operation/gamePgn.

**Comment by niklasf** [comment]
Good catch. By [(unfortunate) design](https://github.com/lichess-org/lila/issues/833), custom starting positions in standard chess are a variant called `fromPosition`, and so variants do not support custom starting positions.
