### ISSUE TITLE
API Feature Request: Embed or GET specific puzzle

### ISSUE THREAD

**Issue by cshancock** [lichess-org/api#183]
Currently users can embed Lichess TV, a study analysis, a specific game, or the daily puzzle, by following the instructions here: https://lichess.org/developers

These features are also available through the API.

It would be nice to be able to embed a specific puzzle in an iframe.

**Comment by benediktwerner** [comment]
https://github.com/lichess-org/lila/issues/11770
https://github.com/lichess-org/lila/commit/854e51a1ee20c0cade1b73a36773c93fcdd07893

There's now an API endpoint to get a puzzle.

If you specifically want to embed puzzles, it's better to create an issue on the main repo.
