### ISSUE TITLE
API Documentation page down.

### ISSUE THREAD

**Issue by RonakKhandelwal** [lichess-org/api#19]
https://lichess.org/api

Page states that something went wrong and gives a stack trace. 

Device: Macbook pro 2015
Browser: Safari
OS: Macos Catelina v10.15 beta. 

Let me know if you need any more information.

Stack trace for reference
---
[native code]
https://cdn.jsdelivr.net/npm/redoc@next/bundles/redoc.standalone.js:93:102375
e@https://cdn.jsdelivr.net/npm/redoc@next/bundles/redoc.standalone.js:101:69021
e@https://cdn.jsdelivr.net/npm/redoc@next/bundles/redoc.standalone.js:121:27035
https://cdn.jsdelivr.net/npm/redoc@next/bundles/redoc.standalone.js:101:74658
https://cdn.jsdelivr.net/npm/redoc@next/bundles/redoc.standalone.js:101:75609
Fa@https://cdn.jsdelivr.net/npm/redoc@next/bundles/redoc.standalone.js:77:69337
wl@https://cdn.jsdelivr.net/npm/redoc@next/bundles/redoc.standalone.js:77:89200
vl@https://cdn.jsdelivr.net/npm/redoc@next/bundles/redoc.standalone.js:77:89125
sl@https://cdn.jsdelivr.net/npm/redoc@next/bundles/redoc.standalone.js:77:86067
sl@[native code]
https://cdn.jsdelivr.net/npm/redoc@next/bundles/redoc.standalone.js:77:45376
https://cdn.jsdelivr.net/npm/redoc@next/bundles/redoc.standalone.js:85:3708
Yo@https://cdn.jsdelivr.net/npm/redoc@next/bundles/redoc.standalone.js:77:45322
Vo@https://cdn.jsdelivr.net/npm/redoc@next/bundles/redoc.standalone.js:77:45257
nl@https://cdn.jsdelivr.net/npm/redoc@next/bundles/redoc.standalone.js:77:82787
enqueueSetState@https://cdn.jsdelivr.net/npm/redoc@next/bundles/redoc.standalone.js:77:49954
https://cdn.jsdelivr.net/npm/redoc@next/bundles/redoc.standalone.js:69:1722
https://cdn.jsdelivr.net/npm/redoc@next/bundles/redoc.standalone.js:101:75234
https://cdn.jsdelivr.net/npm/redoc@next/bundles/redoc.standalone.js:22:2549
a@https://cdn.jsdelivr.net/npm/redoc@next/bundles/redoc.standalone.js:22:1422
promiseReactionJob@[native code]

**Comment by ornicar** [comment]
It works fine. Try with a modern browser such as firefox, chromium or chrome

**Comment by RonakKhandelwal** [comment]
@ornicar I would classify Safari as one of the major browsers, I had already noticed that the page works with firefox but ideally, it should work with safari as well.

**Comment by ornicar** [comment]
Ideally, Safari would work, but I don't think it's my problem here. It's theirs
