### ISSUE TITLE
Updating rated arena tournament makes it non-rated

### ISSUE THREAD

**Issue by vgoloviznin** [lichess-org/api#193]
I'm using the endpoint to update existing tournament: https://lichess.org/api#operation/apiTournamentUpdate

This is the data that I'm passing 

```json
{
  "berserkable": true,
  "streakable": true,
  "hasChat": true,
  "conditions": {
    "nbRatedGame": {
      "nb": 100
    },
    "teamMember": {
      "teamId": "some-team"
    }
  },
  "clockTime": 3,
  "clockIncrement": 0,
  "rated": true,
  "description": "test",
  "variant": "standard",
  "position": "rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1",
  "minutes": 45,
  "name": "some-title"
}
```

The tournament that I'm modifying is *rated*, however after sending request to this endpoint and although I'm passing *rated:true* in the payload, the tournament becomes unrated.

**Comment by ornicar** [comment]
tournaments from a custom position are unrated. Try removing the position from the payload.

**Comment by vgoloviznin** [comment]
@ornicar this worked! 

Although, as far as I understand the position itself is a standard one.
