### ISSUE TITLE
Opening explorer API return moves with "uci" attribute not valid

### ISSUE THREAD

**Issue by fathzer** [lichess-org/api#198]
Hi,

First of all, thanks for providing us with this great API.
Nevertheless, it seems the move encoding in result of Opening explorer has a small problem.
Here is an example:
https://explorer.lichess.ovh/masters?play=d2d4,g8f6,g1f3,g7g6,c1g5,f8g7,b1d2,c7c5,g5f6,g7f6,d2e4,f6d4,f3d4,c5d4,d1d4&topGames=0
The first move returned is a king side castling encoded like that:
```json
{
uci: "e8h8",
san: "O-O"
}
```
Unfortunately, the uci format for this move is not e8h8 but e8g8 (see [UCI specification](http://wbec-ridderkerk.nl/html/UCIProtocol.html))

Best regards,
Jean-Marc

**Comment by benediktwerner** [comment]
Lichess generally uses Chess960 UCI notation wherever possible for consistency and unambiguity.

**Comment by fathzer** [comment]
Thanks for your fast and clear answer. I've learned something :-)
Best regards.
