### ISSUE TITLE
User public data not sent to API access token users

### ISSUE THREAD

**Issue by MarkZH** [lichess-org/api#200]
I'm adding a feature to [lichess-bot](https://github.com/ShailChoksi/lichess-bot/) that would allow users to refuse games against accounts they block and ToS violators. However, when this information is queried from the `/api/user/{username}` access point, the `blocking` and `tosViolation` fields are missing. According to the first comment in issue #159, these fields "never appear in a response to a unauthenticated request." I've tried making tokens with `bot:play` and `web:login` scopes, but these don't work. [A comment on discord](https://discord.com/channels/280713822073913354/436555632964010005/1009862221922324560) says that OAuth tokens are not sufficient authentication for these values.

**Comment by ornicar** [comment]
not yet deployed
