### ISSUE TITLE
Bulk Pairing Create needs 2 additional parameters

### ISSUE THREAD

**Issue by chadejava** [lichess-org/api#204]
Hi Thibs,

I am preparing code for National Online Scholastic Quick Championships that will run on Nov 12-13. We will have bout 1000+ kids for 2 days USCF rated tournament. We like to have these 2 additional parameters when calling Bulk Pairing Create:

1. claimWinOnDisconnection = false
2. giveMoreTime = false

1. USCF does not let players to claim a win when the opponent disconnected, or left the game for whatever reason. Similar to option that the board must be played. So we like to have a board where no one can claim win when a players disconnected, and we have to wait until time forfeits. Please .... :)

2.  Few kids like to add time to their opponents. Well, this should be disable in an option too. We do not want our rounds get postponed because there is a board that keep playing if kids keep adding time on their opponents. Please ... :)

regards

Chacha (Chess Stream)

**Comment by ornicar** [comment]
https://github.com/lichess-org/lila/commit/b78db169724324755841f522908fdc6ad1a040d1

**Comment by ornicar** [comment]
https://lichess.org/api#tag/Bulk-pairings/operation/bulkPairingCreate
