### ISSUE TITLE
"since" query parameter not being respected by API

### ISSUE THREAD

**Issue by maxwell-oroark** [lichess-org/api#211]
I'm trying to use the since query parameter to only fetch games that have been played in the last hour, however when I try to pass a valid unix timestamp to the endpoint I get streamed all games that player has ever played.

ex. ` curl "https://lichess.org/api/games/user/moroark?since=1665881833&pgnInJson=true`

**Comment by ornicar** [comment]
duplicates https://github.com/lichess-org/lila/issues/11729
