### ISSUE TITLE
Bug: API returning wrong analysis

### ISSUE THREAD

**Issue by GavPierce** [lichess-org/api#223]
Around 2 weeks ago there has been a change/bug with the GET api for retrieving analyzed PGNs of a user.
It seems to be incorrectly removing the first move evaluation from a game.

Examples:
Use this endpoint to get the last 5 games of user PaleFischer:
[lichess.org/api/games/user/PaleFischer?max=5&evals=true&analysed=true](https://lichess.org/api/games/user/PaleFischer?max=5&evals=true&analysed=true)

Compare PGN file and it's annotations with the correct analysis of one of those games:
https://lichess.org/A6lQTViX#1
Turn on the engine analysis. And you'll see what the API returns with its analysis is always a half move off!!!

Any ideas?

**Comment by ornicar** [comment]
Already fixed in lila, the new version will be online within a day or two.
