### ISSUE TITLE
`/api/player/autocomplete` Autocomplete endpoint with `?object=true` is returning a non-documented key

### ISSUE THREAD

**Issue by alexrintt** [lichess-org/api#231]
Source: https://lichess.org/api#tag/Users/operation/apiPlayerAutocomplete.

When hitting the endpoint `/api/player/autocomplete` with `object=false` the server response is a simple array of string, as documented:

> `object`: false returns an array of username.

```json
[
  "alexr",
  "alexr7",
  "alexr9",
  "alexr1",
  "alexra",
  "alexrb",
  "alexrc",
  "alexr3",
  "alexrf",
  "alexrd",
  "alexr4",
  "alexr0"
]
```

cURL:

```bash
curl --request GET --url "https://lichess.org/api/player/autocomplete?term=alexr"
```

---

But when hitting this same endpoint with `object=true` the server response is following the schema:

```json
{
  "results": [
    { ...userobj },
    { ...userobj },
    { ...userobj },
  ]
}
```

This is not what the documentation says:

> `object`: true returns an array of user objects `{id,name,title,patron,online}`.

The sample schema also does not include this "results" key:
```json
[
  {
    "name": "Chess-Network",
    "title": "NM",
    "patron": true,
    "id": "chess-network",
    "online": true
  }
]
```

cURL:

```bash
curl --request GET --url "https://lichess.org/api/player/autocomplete?term=alexr&object=true"
```

---

I'm pretty new to this API though, maybe I'm missing an important piece of information related to search endpoints.

**Comment by niklasf** [comment]
Thanks for reporting. Fixed the docs.
