### ISSUE TITLE
CORS error in "export one study chapter" API / JS in browser

### ISSUE THREAD

**Issue by dragunovartem99** [lichess-org/api#237]
Help me, please! Am I doing it wrong?

```js
async function getChapterPGN() {
	const response = await fetch("https://lichess.org/study/***/***.pgn");
	const data = await response.text();
	// Then I do something with data
}
```

I tried to add "no-cors" mode, bearer token with study permissions, tried to write "accept" with "application/x-chess-pgn" in headers, but nothing worked.

But when I suppressed this issue with https://mybrowseraddon.com/access-control-allow-origin.html - everything worked perfectly!

Was this behavior for Study APIs made by design? Or I am doing something wrong?

**Comment by ornicar** [comment]
only endpoints starting with `/api/` can be used from a browser. I'll add one for this use case.

**Comment by dragunovartem99** [comment]
Thank you!
