### ISSUE TITLE
Question: Is HTML the right response for broadcast endpoint?

### ISSUE THREAD

**Issue by cassiofb-dev** [lichess-org/api#246]
Hi, I'm trying to get some broadcast info with lichess api but the return type in the docs and in the actual response seems different. Am I missing something?

## The endpoint I am using
![image](https://user-images.githubusercontent.com/61878987/233807298-654a631a-9901-4fbe-9e7d-e46182373118.png)

## The response I am getting
![image](https://user-images.githubusercontent.com/61878987/233807324-79f6a7a8-fe39-4b86-8f6d-75c853570545.png)

**Comment by niklasf** [comment]
This endpoint requires OAuth (`Authorization: Bearer ...` header). Otherwise it falls back to a non-API page.

**Comment by cassiofb-dev** [comment]
Thanks, that makes sense. I didn't tried with token because it didn't have required label as the other fields.
