### ISSUE TITLE
BOT handling draws

### ISSUE THREAD

**Issue by dlorre** [lichess-org/api#259]
As explained on discord the API documentation does not reference the bot handling draw offer, which is basically the same than board handling draws.

https://lichess.org/api/bot/game/{gameId}/draw/{accept}

https://discord.com/channels/280713822073913354/1023953569071779860/threads/1111332070749380688

**Comment by 0xmessi** [comment]
Is this still open?

**Comment by fitztrev** [comment]
Hi @0xmessi There was a pending PR that I just merged.
