### ISSUE TITLE
Add list of members in a team

### ISSUE THREAD

**Issue by M-DinhHoangViet** [lichess-org/api#274]

**Comment by ornicar** [comment]
https://lichess.org/api#tag/Teams/operation/teamIdUsers

**Comment by M-DinhHoangViet** [comment]
https://lichess.org/api/team/thi-vua-lay-tot-tungjohn-playing-chess/users

**Comment by M-DinhHoangViet** [comment]
Not working

**Comment by icp1994** [comment]
It's a private team, needs oauth.

**Comment by M-DinhHoangViet** [comment]
Oauth? How to ?

**Comment by icp1994** [comment]
Please ask in https://discord.gg/lichess - not here.

**Comment by M-DinhHoangViet** [comment]
Ok, I made the mistake of testing the private team
