### ISSUE TITLE
Chapter ID list error

### ISSUE THREAD

**Issue by a-wille** [lichess-org/api#284]
When I tried loading a particular study (shared from a friend of mine, otherwise I would provide the study id here), although the regular non-API html document provides a list with the correct names and chapter IDs for each chapter in the study, the API request returns 6 chapters as having the same chapter ID, which isn't accurate. This may be due to the fact that this study is semi-private on lichess. I hadn't encountered this issue until one particular study. Not sure why it has this random bug.

**Comment by ornicar** [comment]
> I hadn't encountered this issue until one particular study. Not sure why it has this random bug.

Sounds like we'll need the study ID to reproduce then fix the bug.
