### ISSUE TITLE
button auto-disable draw offer

### ISSUE THREAD

**Issue by sl5net** [lichess-org/api#303]
I believe that this is a popular opinion among chess players, and I hope that Lichess will consider implementing this feature.

Proposed solution:

Add a new configuration option in the settings menu to allow players to disable draw offers in the last 5 seconds of a game.

Add another configuration option to allow players to limit the number of draw offers that a player can make in a single game.

Or maybe also a button auto-disable draw offer.

Benefits:

    Reduces frustration for players who find last-minute draw offers disrespectful.

```
7:44
: eventually a idea to make it configurable when draw is allowed (e.g. not in the last seconds and not more often then x times) or so
7:45
: Right, there should be a configuration setting on when draws are allowed and draws aren't
7:45
: I get what he's saying
```

Thank you for your time and consideration.

**Comment by icp1994** [comment]
I think you opened the issue in the wrong repo - try https://github.com/lichess-org/lila instead
