### ISSUE TITLE
Lichess API documentation links #2

### ISSUE THREAD

**Issue by Mercutio1243** [lichess-org/api#308]
One addition to my earlier post,  the following links are also not working:

> API demo app with OAuth2 login and gameplay: source / demo
> API UI app with OAuth2 login and endpoint forms: source / website

**Comment by fitztrev** [comment]
The links appear to be working now. If it's still happening, can you post the URL?

There is a possible issue with Chrome security settings now giving a warning because of `lichess-org` subdomain so that may be the problem?
