### ISSUE TITLE
Game created by API, only one player get notification

### ISSUE THREAD

**Issue by chadejava** [lichess-org/api#31]
I am able to generate token with oAuth2. I have for player 1, and I have for player 2. I am also able to create game for both players. What I did was requesting game from Player 1 to Player 2. Put token Player 1 in Bearer, then put Token Player 2 in acceptByToken. It worked. The slight problem is that Player1 got notification (join the game), but player 2 did not get notification. Player 2 is still able to play a new other game, while player 1 can't do that without canceling the request.

**Comment by ornicar** [comment]
You should give the players the link to the game, using the ID generated by the API call to create it.

**Comment by chadejava** [comment]
Yes. I can do that. Thanks. You asked me (from #programing at discordapp)
to submit this ticket, that is why this ticket is here.


regards


Chacha
