### ISSUE TITLE
Bot takeback handling is undocumented

### ISSUE THREAD

**Issue by MarkZH** [lichess-org/api#321]
I'm working on adding move takeback handling to lichess-bot. I looked at the API and did not see a section for bots handling takeback requests. There is [such a section for the Board API](https://lichess.org/api#tag/Board/operation/boardGameTakeback). I tried using the bot API with the same interface (`/api/bot/game/S0zmk7jS/takeback/yes`) and it worked. Is this a case of documentation oversight, or is this feature not official yet?

**Comment by fitztrev** [comment]
Documentation missing. Can be added.

**Comment by jalpp** [comment]
hey I will take care of this 👋
