### ISSUE TITLE
dark mode support?

### ISSUE THREAD

**Issue by jalpp** [lichess-org/api#335]
the current doc UI is light mode based, dark mode be much help as many devs prefer dark mode over light mode

I was playing around and made this

![Screen Shot 2024-04-13 at 11 09 49 AM](https://github.com/lichess-org/api/assets/92553013/87d6b2c5-da57-4363-bf3e-86b07d9449f9)

Certainly not entirely dark mode, but at least gets there, I tried making the centre pannel dark blueish but didn't really work.

**Comment by jalpp** [comment]
I can shoot a PR if the maintainers are interested otherwise locally Im happy to use this version, than the old one

**Comment by fitztrev** [comment]
Thanks. Would prefer to keep Redocly easily upgrade-able without worrying about maintaining custom styles.
