### ISSUE TITLE
Need "Login With Different Account" on OAuth page

### ISSUE THREAD

**Issue by chadejava** [lichess-org/api#34]
Just suggestion. On https://oauth.lichess.org/oauth/authorize (oAuth page), can we have button that says "Login With Different Account"? We do oAuth on Tournament registration, and some parents have multiple kids to register, so after a parent register one child (oAuth completed), then register another child, on that page they lost (need to logout and try register again and so on ...)

regards

Chacha

**Comment by ornicar** [comment]
Please post on https://github.com/ornicar/lichess-oauth-server

Note that I won't touch that PHP codebase.
