### ISSUE TITLE
Add documentation for block + unblock endpoints

### ISSUE THREAD

**Issue by fitztrev** [lichess-org/api#352]
https://github.com/lichess-org/lila/blob/f48a2f13dd61a9ec5c8e6ca967fb6e4c6eb2f65e/conf/routes#L51-L52

See existing docs for follow/unfollow for example:

https://github.com/lichess-org/api/blob/658e06fb2cffaa1ade7aaffc39174d66c406addc/doc/specs/lichess-api.yaml#L539-L543

**Comment by jalpp** [comment]
Hey, I can take care of this please assign to me

**Comment by fitztrev** [comment]
@jalpp would you still like this?

**Comment by jalpp** [comment]
Hey! Yes sorry been busy for something else I would get to it soon
