### ISSUE TITLE
`broadcastTourCreate`/`broadcastTourUpdate` and `broadcastRoundCreate`/`broadcastRoundUpdate` need update

### ISSUE THREAD

**Issue by SergioGlorias** [lichess-org/api#358]
With recent updates to broadcasts, the documentation is no longer valid.

**Comment by fitztrev** [comment]
Which fields specifically? For the request or response? And is it just the example JSON or the schema too?

**Comment by SergioGlorias** [comment]
In case I haven't tested the new variables yet
but they are the same variables as on the website forms
each form input is valid from the API

`https://lichess.org/broadcast/new`
`https://lichess.org/broadcast/{broadcastTournamentId}/edit`
`https://lichess.org/broadcast/{broadcastTournamentId}/new`
`https://lichess.org/broadcast/round/{broadcastRoundId}/edit`

but example: in create/edit Broadcast
- `description` is now `info.format`, `info.tc` and `info.players`
