### ISSUE TITLE
Create multiple challenges

### ISSUE THREAD

**Issue by Beddie** [lichess-org/api#36]
Part of learning chess, a group of young chess students receives a challenge based on a position in lichess to solve themselves and play interactively against 1 trainer. This is kind of a simultane but different because a particular position is used (fen based) and after new insights are gathered and students understand the position a different position will be challenged to the same group. Sometimes this position is slightly different than the position used before, for example in a training we look at the case when the pawn on A6 is on A7 and then try to learn from that position plus we discuss what a difference it makes and let the students play the position themselves again against the trainer in lichess.
The api call to https://lichess.org/api/challenge/{username} (which is send from an app we created) is perfectly capabel for this purpose and works fine initially but after this api call is used several times for 1 token the lichess api responds with a 404 error.

Addidional info:
- @ornicar asked to create a use case after a discord chat we had about this issue.
- Our chess club has more than 100 members and we are planning to integrate lichess into our online training program. The api call to create challenges will be used a lot in this case.

**Comment by niklasf** [comment]
Same as ornicar/lila#7939?

**Comment by ornicar** [comment]
seems so
