### ISSUE TITLE
Need API for update/delete created games

### ISSUE THREAD

**Issue by chadejava** [lichess-org/api#37]
Being tournament organizer, sometime we need to correct board/game we have created. We are able to create board/game for 2 players base on their OAuth. Please add an update/delete method to correct those board if needed (limited to the boards that we created only):
- delete/cancel the board. even if players are playing in it.
- update time control on the board

regards

Chacha

**Comment by Aditya-132** [comment]
Can I work on this issue

**Comment by ornicar** [comment]
This will abort the game https://lichess.org/api#tag/Challenges/operation/challengeCancel

We won't support deleting started games or changing time control during the game.

**Comment by Aditya-132** [comment]
> This will abort the game https://lichess.org/api#tag/Challenges/operation/challengeCancel
> 
> We won't support deleting started games or changing time control during the game.

So will I have to work on it or it is already done

**Comment by ornicar** [comment]
There's nothing to do.
