### ISSUE TITLE
[QUESTION] Duplicated tags in PGN headers allowed?

### ISSUE THREAD

**Issue by cakiki** [lichess-org/api#381]
Hello,

I noticed this duplicated `Event` tag in the PGN schema example: https://github.com/lichess-org/api/blob/master/doc/specs/schemas/GamePgn.yaml#L20 and was wondering if this was an oversight, or whether PGNs can have repeated tags in the header.

**Comment by niklasf** [comment]
Good catch. http://www.saremba.de/chessgml/standards/pgn/pgn-complete.htm#c8.1 says

> The same tag name should not appear more than once in a tag pair section.

and PGNs like that shouldn't be produced in any case.
