### ISSUE TITLE
Trying to stream board using serverless architecture but CORS

### ISSUE THREAD

**Issue by lropero** [lichess-org/api#43]
Hi, I'm using Lambda functions to perform OAuth2 authentication and everything works fine until I want to stream the board by calling the `/api/board/game/stream/{gameId}` endpoint. Since I receive a NDJSON ReadableStream response which leaves the connection open I can't make this work from a serverless function since it times out after some time and closes the connection.

So my solution to keep this architecture was to break a bit the security and allow the browser to request the access token (which is stored in a HTTP only, same site cookie) and have the browser open this connection client-side. Problem is that I receive a `cors` type fetch response and I'm unable to receive any data at all.

<img width="418" alt="Captura de Pantalla 2020-07-03 a la(s) 13 37 31" src="https://user-images.githubusercontent.com/4450399/86486704-66dd1200-bd32-11ea-8208-20cb41d7dd22.png">

I know that by avoiding the whole serverless idea and deploying a full API on Heroku as opposed to Lambda functions would definitely make this work, but is there a way to have this working under the serverless paradigm?

**Comment by niklasf** [comment]
Can you please show a snippet of the `fetch()` call, and screenshots of requests and responses from devtools? CORS should be supported on this endpoint.
