### ISSUE TITLE
API LTI compliance or improved result handshaking?

### ISSUE THREAD

**Issue by chairCIC** [lichess-org/api#47]
Hi,

I'm the Chair of the Chess Institute of Canada. Because of the pandemic, we've had to rapidly swap all our in-class teaching in elementary schools to online. So we've obviously looking at LiChess, but we've also have been looking at full blown Learning Management Systems [LMS] like Moodle and Sakai.

Most of these packages have Learning Tools Interoperability [LTI] so lower level learning tools [like LiChess] can handshake results back. I think LTI is a complex model, since they take great steps via encryption to avoid hacking and cheating on results. [All the folks that take the online Java course always get 100% oddly...]

The current LiChess API is pretty good, but we'd be looking for results like did the student complete the LiChess activity, and how long they took to do so. Some of the functionality is already in the API, it's pretty close. Rather than a fullblown LTI implementation, I'd just be happy with some more handshaking. [I ain't worried about cheating frankly!]

i wish I knew more Java to help. My knowledge is beyond ancient, mainframes, UNIX, assembler, C. <g>

LiChess is fabulous. Do think hooking it to LMS is the way to go. I need something we can scale to 800 schools or more. When you are teaching 50,000 kindergarten to grade 4 kids asynchronously, you need a lot of automation!

with thanks to the community,

Michael Sutton
Chair CIC

**Comment by ornicar** [comment]
What do you mean by "handshaking"?

Which endpoints do you need created or extended?

**Comment by chairCIC** [comment]
Hi Thibault,

Thanks for getting back to me. My knowledge of Java is poor. We were
looking for some kind of functionality if a puzzle [or perhaps a  study]
object was invoked via the API, that some kind of token or tokens could be
returned that indicated a) was the object completed successfully b) how
long did that solution or study take?  The idea with an LMS [Learning
Management System] you often have asynchronous teaching [what that means is
there is no "live: or interactive human teacher watching what you do] so
the student would do some kind of Chess lab, the LMS would evaluate their
performance, and the human teacher can eventually look at the results and
see how well or poorly they are doing. With the pandemic and children
having to be in small groups or pods we get into a teacher shortage
rapidly. So anything we can do online and evaluate in an automated fashion
via software really, really helps.

The formal convention is LTI [or Learning Tools Interoperability] but that
seems a complex standard designed to encrypt the traffic and deter
cheating. I'd just be happy if the API returned a few tokens to evaluate.
[JSON tokens or strings? Is that the Java convention for parameter passing?]

with thanks,

Michael
