### ISSUE TITLE
Is filtering working on /games/export ?

### ISSUE THREAD

**Issue by tailuge** [lichess-org/api#5]
I would expect the following to fetch my last two analysed games but it also returns unanalysed ones.

curl 'https://lichess.org/games/export/tailuge?analysed=1&evals=1&max=2'

Also the old interface https://en.lichess.org/api/user/"+player+"/games?nb=100&with_analysis=1&page=1
included the judgement information (i.e. blunder,mistake,inaccuracy). Are there any plans to support json responses for games like this in the new API?  Should I stop using the old API?

**Comment by ornicar** [comment]
The fixes are on https://listage.ovh.

I'm adding JSON support.

**Comment by ornicar** [comment]
JSON support is available on stage. https://lichess.org/api#operation/gamesExportUsername select `application/x-ndjson` on the right side

**Comment by ornicar** [comment]
Now on prod.

**Comment by tailuge** [comment]
yep confirmed it works on prod and also contains the extra info in the json. I'll switch my old programs to use it - feel free to shut off the old API anytime.
