### ISSUE TITLE
Potential issue with the open challenge api endpoint

### ISSUE THREAD

**Issue by th0masb** [lichess-org/api#55]
Hi, I am experiencing something a bit strange with the open challenge endpoint in that there seems to be an issue with the limit field, the only value which seems to work is 0. For example this curl works fine:

`curl -X POST -d "clock.limit=0&clock.increment=10" https://lichess.org/api/challenge/open`

but this doesn't:

`curl -X POST -d "clock.limit=1&clock.increment=10" https://lichess.org/api/challenge/open`

In fact any non-zero limit value seems to cause an error. Am I misunderstanding something or this a bug?

**Comment by ornicar** [comment]
```
curl -X POST -d "clock.limit=300&clock.increment=10" https://lichess.org/api/challenge/open
{"challenge":{"id":"RIuMgjkt","url":"https://lichess.org/RIuMgjkt","status":"created","challenger":null,"destUser":null,"variant":{"key":"standard","name":"Standard","short":"Std"},"rated":false,"speed":"rapid","timeControl":{"type":"clock","limit":300,"increment":10,"show":"5+10"},"color":"random","perf":{"icon":"#","name":"Rapid"}},"socketVersion":0,"urlWhite":"https://lichess.org/RIuMgjkt?color=white","urlBlack":"https://lichess.org/RIuMgjkt?color=black"}
```

Works just fine. As stated in the API doc, the limit is in seconds.

**Comment by th0masb** [comment]
Ah so the limits has to be divisible by 60... Might be worth adding that into the doc or having a better error message! Thanks.
