### ISSUE TITLE
Replace string in example by int

### ISSUE THREAD

**Issue by tmmlaarhoven** [lichess-org/api#64]
In https://github.com/lichess-org/api/blob/master/doc/specs/lichess-api.yaml on line 3876 (context given in case line numbers change):

    PuzzleRoundJson:
      example: {
        "id": 70232,
        "date": 1514505150384,
        "rating": "1982",
        "ratingDiff": 5,
        "puzzleRating": 1877
      }

The "rating" should return an int (and I think it does), but the example suggests it returns the rating as a string.

**Comment by niklasf** [comment]
Indeed, thanks. Checked the source and it appears to be an int.
