### ISSUE TITLE
JSON exports of games from api doesn't have players' real names using the players parameter

### ISSUE THREAD

**Issue by icp1994** [lichess-org/api#67]
From the game api when trying to export a game as json with `pgnInJson` parameter, neither the `user` fields nor the included pgn has the players' real names when using the `players` parameter. Exporting as pgn works as intended though. Tried with `#operation/gamePgn`, `#operation/apiUserCurrentGame`, and `#operation/apiGamesUser`. In all cases the pgn exports work as intended.

Example requests:

- `curl -H "Accept:application/json" -sS "https://lichess.org/game/export/fg59gH3A?pgnInJson=true&players=https://gist.githubusercontent.com/ornicar/6bfa91eb61a2dcae7bcd14cce1b2a4eb/raw/768b9f6cc8a8471d2555e47ba40fb0095e5fba37/gistfile1.txt"`
- `curl -H "Accept:application/json" -sS "https://lichess.org/api/user/stl_caruana/current-game?pgnInJson=true&players=https://gist.githubusercontent.com/ornicar
/6bfa91eb61a2dcae7bcd14cce1b2a4eb/raw/768b9f6cc8a8471d2555e47ba40fb0095e5fba37/gistfile1.txt"`
- `curl -H "Accept:application/x-ndjson" -sS "https://lichess.org/api/games/user/stl_caruana?max=1&pgnInJson=true&players=https://gist.githubusercontent.com/ornicar/6bfa91eb61a2dcae7bcd14cce1b2a4eb/raw/768b9f6cc8a8471d2555e47ba40fb0095e5fba37/gistfile1.txt"`

**Comment by ornicar** [comment]
Only the PGN tags have the player name replacements,
as explicitely mentioned in the API documentation.

The idea is that if you're getting JSON,
then you can manipulate it and do the needed replacement yourself.
Whereas PGN is often passed directly to replay software,
hence why lichess offers to modify it at the source.

**Comment by icp1994** [comment]
I was curious why the other query parameters such as `clocks` and  and `evals` changed the pgn included in the json as the `pgn` filed but not this one in particular. But anyway it's not a big deal; thanks for the reply :+1:

**Comment by ornicar** [comment]
I did update the pgnInJson with the commit above
