### ISSUE TITLE
endpoint for Coach page

### ISSUE THREAD

**Issue by salsan** [lichess-org/api#68]
I ask if is possible to create a endpoint for coach page and extract reviews from it

**Comment by ornicar** [comment]
I ask what is your use case

**Comment by salsan** [comment]
I plan to build a landing page for my [brother](https://lichess.org/coach/newbie87) and I want to add a review section

**Comment by ornicar** [comment]
I won't mind if you do webscrapping on this one. There's no plan to add such an API for the forseeable future
