### ISSUE TITLE
Translation insufficient for tournament threshold

### ISSUE THREAD

**Issue by Hypenate** [lichess-org/api#71]
I current have a rating if 1497, I tried to enter a <1500 Rapid tournament, which I could not.
![image](https://user-images.githubusercontent.com/7478681/99637532-485b8700-2a45-11eb-8267-818ac817e1ed.png)
This looked strange to me first, but when I enabled the "participate" button in HTML and clicked on it, it showed the following alert:
![image](https://user-images.githubusercontent.com/7478681/99637738-8fe21300-2a45-11eb-82eb-de12aebbc864.png)
> Your best highest rating this week Rapid (1504) is too high

Thus I would like to change the translation of:
![image](https://user-images.githubusercontent.com/7478681/99637411-19451580-2a45-11eb-800e-c781a9ac04f4.png)
to something like:
```
Rated ≥ %1$s in %2$s this week
Rated ≤ %1$s in %2$s this week
```

**Comment by niklasf** [comment]
Moved to https://github.com/ornicar/lila/issues/7614
