### ISSUE TITLE
getting other people's information

### ISSUE THREAD

**Issue by ctfrancia** [lichess-org/api#74]
I am creating an api. What I am trying to do is have someone put in their `lichess username` and then when they press submit I can call your API and get their information such as: bullet, blitz, classical, etc rating just to make it easier so they don't have to go to yoursite, login(if they need to) etc. I see that with the token it is linked to the person that created it (me for example) and then when making a curl to the link I get an HTML response and would rather not have to scrape it. Did I miss the docs that says where I could get the information?

**Comment by niklasf** [comment]
Sounds like https://lichess.org/api#operation/apiUser, which works for arbitrary usernames.
