### ISSUE TITLE
Puzzles endpoint?

### ISSUE THREAD

**Issue by charlesoblack** [lichess-org/api#82]
Are there plans for an endpoint to get puzzles and puzzle-related perfs? Something similar to what's displayed in the puzzle dashboards or the per-category perfs/to-replay puzzles.

**Comment by niklasf** [comment]
https://lichess.org/api#operation/apiPuzzleDashboard has been implemented via ornicar/lila@1313b91e726ef9b4c06c5f25ad312512b3b3abf2 :tada:

**Comment by charlesoblack** [comment]
Thanks!
