### ISSUE TITLE
Perhaps https://lichess.org/tv/channels doesn't need to be SameOrigin

### ISSUE THREAD

**Issue by JohnChernoff** [lichess-org/api#84]
Unless there's a good reason otherwise, it would be nice to have less fettered access to this particular endpoint.

Thanks,

- John
-

**Comment by niklasf** [comment]
Will do. Pull request sent: https://github.com/ornicar/lila/pull/8063.

**Comment by niklasf** [comment]
The endpoint will be moved from `/tv/channels` to `/api/tv/channels` and then support CORS. Will be deployed with next site update.

**Comment by JohnChernoff** [comment]
Yay,

Thanks. :)
