### ISSUE TITLE
Get Studies of User API

### ISSUE THREAD

**Issue by Frank-L93** [lichess-org/api#91]
Hi,

It would be wonderful if we had a /study/{user}/{optional-auth} endpoint to get a list of all studies-id of a specific user (including private studies if auth is implemented (maybe not necessary as you can also embed private studies, so they are not really private if you know the ID).

Use-case is to easily generate embedded studies on for example a club site, instead of copying all the links manually;
A little bit of a example on what I mean can be seen on https://franklambregts.com/deepdives 

Don't know if this is the good way to request this. Thanks anyway!

**Comment by ornicar** [comment]
private studies cannot be embedded. Only unlisted studies can.
