### ISSUE TITLE
Two-sided challenges

### ISSUE THREAD

**Issue by WinTDoan** [lichess-org/api#93]
I'm sure this has been a past feature request, but I would like to re-iterate it. We have fairly successfully used Lichess for high school team chess in Illinois U.S.A. in the past year. However, there are certain aspects of it that are a bit complicated and one would hope could be improved with a new API method.

First, note that the current bulk pairings would be rather clumsy---collecting authcodes from literally thousands of players, in advance, just isn't feasible. The bulk pairings might work if it were possible to harvest authcodes so the process could be better automated (if some method were associated with the authcode that allowed userid=xxxx to query for it).

As it stands, the way it works is that each team sets its roster for a round. When the round is paired, a list of who played white and who black on each board is made available. Conventionally, the player with Black uses that to generate a challenge, and, if it appears to be correct, White accepts. Since the players (and not the TD) actually make the challenge, it's then necessary to harvest the game ID's to keep track of the results. It works, but it's very clumsy. Sometimes, Black gets the parameters wrong. Sometimes Black is slow to get the challenge out and the game starts five minutes late. Sometimes, White sends the challenge with the wrong colors.

If making authcode harvesting simpler isn't possible, what about something like an open ended challenge, but with specific players ID's for white and black. Both players have to accept to create a game, but the TD is able to make sure it's the correct players, with the correct colors and is able to get the game ID right away.

**Comment by ornicar** [comment]
The right way to collect oauth codes is through an application that logs in with lichess. You'll find an example here: https://github.com/lichess-org/api/tree/master/example/oauth-authorization-code

It's the serious way to do it, but it does require some technical work.

I could also be possible for teachers to generate the tokens for their class students. Would that be useful?

As for your request of enforcing player names of an open-ended challenge, that sounds reasonable to me, I'll try it out now.

**Comment by ornicar** [comment]
Wait, I think your use case is already handled. You say you want "the TD is able to make sure it's the correct players, with the correct colors and is able to get the game ID right away".

You can already have exactly that, using the [open challenges endpoint](https://lichess.org/api#operation/challengeOpen):
- the response has a `urlWhite` and `urlBlack` fields that you can give to each player so they get the correct color
- the response has an `id` field that contains the game ID (which is the same as the challenge ID)

**Comment by WinTDoan** [comment]
Thanks. That just about will do it.

1. It doesn't look like the "rated" attribute is available. (Which is odd 
because the example response seems to have rated on).

2. It would be nice to have a message on the challenge instead of 
just "Open Challenge". If I could replace that with "Sterling 
Tournament, Round 2" it would be great.

> Wait, I think your use case is already handled. You say you want "the
> TD is able to make sure it's the correct players, with the correct
> colors and is able to get the game ID right away".
> 
> You can already have exactly that, using the [open challenges
> endpoint](https://lichess.org/api#operation/challengeOpen): - the
> response has a `urlWhite` and `urlBlack` fields that you can give to
> each player so they get the correct color - the response has an `id`
> field that contains the game ID (which is the same as the challenge
> ID)
> 
> -- 
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/lichess-org/api/issues/93#issuecomment-800979213


---
2717 Harrison St
Evanston, IL 60201
USA

**Comment by ornicar** [comment]
Not sure about the challenge name, since only one of the two players will ever see it (the first one to click)

**Comment by WinTDoan** [comment]
Is that true? The way it seems to work (at least with the White and 
Black URL's) is that each player could separately enter the URL 
which then asks each if they want to "Join". They haven't accepted 
the challenge until they do that, so those could be displayed 
simultaneously.

> Not sure about the challenge name, since only one of the two players
> will ever see it (the first one to click)
> 
> -- 
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/lichess-org/api/issues/93#issuecomment-802376151


---
2717 Harrison St
Evanston, IL 60201
USA
