### ISSUE TITLE
Cant make it work

### ISSUE THREAD

**Issue by 9acca9** [lichess-org/api#94]
Hi.
Sorry the ignorance... i cant make it work.
Im trying to install this: https://github.com/lichess-org/api/tree/master/example/board-api

By the way building the front-end i get this error.

```
rc/main.ts → ../back/public/dist/app.dev.js...
(!) Plugin typescript: @rollup/plugin-typescript TS1110: Type expected.

6 export declare type SquareName = `${FileName}${RankName}`;
                                   ~~~

created ../back/public/dist/app.dev.js in 3s
Done in 3.44s.
```
there is a lot of this "`" on the code... i dont know much about coding... but it look like maybe that is the problem??? (i dont find that sentence to try to change it)...
(just asking, as i say... i dont know much about coding)

Thanks.

**Comment by niklasf** [comment]
Are you using npm or yarn?
