### ISSUE TITLE
Message not sent when calling api/bulk-pairing

### ISSUE THREAD

**Issue by 6heads** [lichess-org/api#96]
As far as I understood it, a message should've been send when the api returns 200.

I successfully setup a pairing, but none of the players received a message. Did I understood something wrong?
Or does the creator don't receive messages? 
My other test accounts were restricted to kids mode, so they won't receive a message. How are those supposed to play/join? Wouldn't a notification be better?

Another question regarding the documentation to messages. It says:
`{opponent} and {game} are placeholders that will be replaced with the opponent and the game URLs.`
Are there any other placeholders like {player}?

**Comment by ornicar** [comment]
I just tried and the players do receive the message, whether they're kid accounts or not.

Maybe give more details to help me reproduce the problem? I'm responsive in the discord API channel

**Comment by 6heads** [comment]
As I wrote on discord I didn't get a notification/message when I put the date close to the max of +24 hours. 
Maybe the message is sent a few hours before the start of the game?

But there is more.
If one player is a child, the adult will receive a notification, but no message. The kid won't receive anything. 
You told me that this is to protect the kids.
For the kids side this is reasonable, but why not sending a message to the adult?
The game will start nonetheless so it doesn't make a difference if you join via message or lobby.

Imo bulk pairings are more or less the same as challenges and as an adult you can challenge a child if you wish.
Maybe it would be nice to have a notification on the challenge-symbol when the game is about to start? This way even kids could join.

A slightly modified waiting screen would be nice - if I had a wish:
![image](https://user-images.githubusercontent.com/46749895/113930900-25622180-97f2-11eb-823a-78a68220f740.png)
