### ISSUE TITLE
API function to terminate an arena tournament

### ISSUE THREAD

**Issue by TM90** [lichess-org/api#97]
It is possible to create arena tournaments with the API but not possible to terminate a created one. Especially for tools automatically creating tournaments errors may happen and a terminate method would be helpful.

**Comment by ornicar** [comment]
I think you should also post that in ornicar/lila. Could be a good first issue for a scala dev.

You would be personally using that new endpoint, right?

**Comment by niklasf** [comment]
Closing this one.
